# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.12.0-browsers

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
       # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      # run lint
      - run: npm run lint

      # run tests
      - run: npm run test

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      # will add github as known host
      - checkout
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "31:19:97:06:2b:8b:a1:b2:62:d2:18:10:c4:62:ee:44"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - run:
          name: Publish package
          command: "npm run publish -- --yes"

  docs-build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build docs
          command: sudo apt install rsync && npm run docs
      - persist_to_workspace:
          root: ~/repo
          paths: docs

  docs-deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: docs
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "5d:d2:63:74:76:80:77:e9:29:55:b0:9d:ab:56:66:5d"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - docs-build
      - docs-deploy:
          requires:
            - test
            - docs-build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
